cookie:
  expiry_days: 0
  key: random_signature_key
  name: random_cookie_name
credentials:
  usernames: !!binary |
    Z0FBQUFBQm0tbFB0SFVyZzhsRzFqdUJ6QlE4S3dLTWdid0dOWHpZWGFDcFc1X0plak1iWlRJSlJ1
    R0ItQ2pvcFJpdGM5SHVid1JPYy1fUmFGR0RyQzZLcGJPaWlVTXN1SXRSSGNsLTBiQmlGd1dSWXdf
    cUgwUEhxLXM3OW1KUVZ1TlFfS2FDTWl5SjhjSk80cDJVQ1g4Snc1Q0x4OUlFMGE4ZWVFUndqTzhB
    MzRCaTRTcmlGbVk4QVJWNVRWWTNZVlU1T1FVcjZEOC1GLV8xYm5CRVhZYUVDZDBPcmtNSTBGWkhB
    ZlhMbGZ3M0lhSUF6VzZZM25oQTM3Vy1zMVBmNTFkTVUzUllWbDF0cnlYYTVmanJfOE9sZDFXbnpF
    ejd6cXJKOV80TFZlX2hZVHkyWV9NVXRrMnNfSjZ0Q2tKbXBJSVhuMy04eGtPT3hDSFhhazJlcEJG
    SDFoWVJoSWhWVm93PT0=
