cookie:
  expiry_days: 0
  key: random_signature_key
  name: random_cookie_name
credentials:
  usernames: !!binary |
    Z0FBQUFBQm5BSk1UMXo4Tko5VG5RdEl5TTREa3FkWS1hQnozcE80UmUyWlRDNE53SkJOYm1JeWJa
    T0ZmOFBXb2N1VjFzREVLb200bHc5ZV9adUFmWG12cDMxa3cwTG5qbnVodDNjT2hHRDVHajRwTDBp
    SkFlSVJTUHhvSjR3aC1XcVpWWDlFLWVkaEpuOXl2eHg1YVV1QnRYcEtUM0c3VS15TV9VZGN5VzJv
    ZzhmeHd6c2R1ckJDdVFLS3VZTFdWdjE3V2lJdU8yVURmMjE4MGo3OFctYkExcUkxMUVkNjIyS2l4
    Q0pSQ20wTnpWT1dDeGxQWkkya05VWTR1aDVRRkdyYS1aWVJYRnZ6VjhvT0dGdThtLTlPRU1WX0tL
    YlZYSC02eThINEVGZlRFYUVYY1o0bGJJaDl2d1hhaXpmZnd1WldDUGdrUlBEakJuMmowYVJZSjBU
    UlNHMzlZdnJkNzZnPT0=
