cookie:
  expiry_days: 0
  key: random_signature_key
  name: random_cookie_name
credentials:
  usernames: !!binary |
    Z0FBQUFBQm1fWkNTaGduMF9pSTBXeU94OTdYVjZ3ZDI4VnQwNnpkY1RGLWg1NmlhdEU3ZEo0dkp0
    RWxzMkdQUnE1eXRzZmxMbFJMcnJiMmNYX0JCbXlNaUpCR0dRV2twV012bnN5aUxWVVNKenRHZVc2
    Uy16NThHMHZxWHJTbmlnMkpaQ1RrS28xWmh0anNVbzJsM3Q5M01pNVc3OEtQUmlNZ1BNRVBCZy10
    SHpmVlRSZks2NE1STlBfMi1GakhhdkJLMng2Z0oyMVpoUENIaDhrMF91R0VmMDN3cVdCSjdmWVN1
    RS1OQks5NkxGZmJ4U0pPTVFjaVA3UU1ZanRvUG9KSDZaaFZqT01YQzd0OUpYbUhYOGtUQTZZaWtK
    ZTNfbjIzdzVnQklzVjBoOGpHOHJndVNheDJrOFZmdjI4Q01HX0lUdFBRajg1ZFhLVFVyTWRVYkhZ
    M04wNUVjS212bWVRPT0=
